title: Coffee Bean Sales Market Analysis
--logo: /assets/img/headshot_circle.png
--#description: Coffee Bean Sales
theme: jekyll-theme-minimal
minimal:
  show_repo_link: false
  show_downloads: false
  search: false
  skin: auto
plugins:
  - jekyll-feed
include: ["assets/css"]
classes: wide
